// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6xfkP6Wav33czALsukSdLWV2cenWyiY',
    appId: '1:787851180749:web:b8a616b0d57321fd578784',
    messagingSenderId: '787851180749',
    projectId: 'ecommercedada-c8550',
    authDomain: 'ecommercedada-c8550.firebaseapp.com',
    storageBucket: 'ecommercedada-c8550.appspot.com',
    measurementId: 'G-CSNGR66QWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASt5fsf1PjGrxrLORGJwUem_2MhWiLZus',
    appId: '1:787851180749:android:21b6c21fc4225fd9578784',
    messagingSenderId: '787851180749',
    projectId: 'ecommercedada-c8550',
    storageBucket: 'ecommercedada-c8550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GhqJYyhfyYWzrBQwhvjrCtgcavk3aK0',
    appId: '1:787851180749:ios:ca161699dcde48c4578784',
    messagingSenderId: '787851180749',
    projectId: 'ecommercedada-c8550',
    storageBucket: 'ecommercedada-c8550.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7GhqJYyhfyYWzrBQwhvjrCtgcavk3aK0',
    appId: '1:787851180749:ios:8281c3e03e9def61578784',
    messagingSenderId: '787851180749',
    projectId: 'ecommercedada-c8550',
    storageBucket: 'ecommercedada-c8550.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
